/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import javax.swing.border.Border;
//
/**
 *
 * @author USER
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public void timeanddate(){
        final DateFormat dte = new SimpleDateFormat("yyyy/MM/dd");
        final DateFormat tme = new SimpleDateFormat("hh:mm:ss aa");
        DateFormat dateFormat = new SimpleDateFormat("hh.mm aa"); 
                Timer timer = new Timer(1000, new ActionListener() {
        @Override
            public void actionPerformed(ActionEvent e) {
//                Calendar cal = new GregorianCalendar();
//                int second = cal.get(Calendar.SECOND);
//                int minute = cal.get(Calendar.MINUTE);
//                int hour = cal.get(Calendar.HOUR);
//                time.setText("Time " + hour +":"+minute+":"+second);
                Calendar now = Calendar.getInstance();
                time.setText("Date -" + dte.format(now.getTime()));
                date.setText("Time -" + tme.format(now.getTime()));

            }
        });
        timer.setInitialDelay(0);
        timer.start();
    }
    public main() {
        initComponents();
        timeanddate();
        //returnbook.setBackground(new Color(255,255,255, 100));
        //adduser.setBackground(new Color(255,255,255, 100));
        //idcard.setBackground(new Color(255,255,255, 100));
        //inventroy.setBackground(new Color(255,255,255, 100));
        //newentry.setBackground(new Color(255,255,255, 100));
        //userinfo.setBackground(new Color(255,255,255, 100));
        
        jPanel3.setBackground(new Color(255,255,255, 100));
        
        jPanel4.setBackground(new Color(240,240,240, 150));
        jLabel1.setForeground(new Color(255,255,255));
        jPanel3.setBackground(new Color(255,255,255, 100));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        adduser = new javax.swing.JLabel();
        newentry = new javax.swing.JLabel();
        idcard = new javax.swing.JLabel();
        userinfo = new javax.swing.JLabel();
        inventory = new javax.swing.JLabel();
        returnbook = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1092, 452));
        setSize(new java.awt.Dimension(1092, 452));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 170, 20));

        time.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 170, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1090, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adduser.setBackground(new java.awt.Color(255, 255, 255));
        adduser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        adduser.setForeground(new java.awt.Color(0, 102, 255));
        adduser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adduser.setText("Add New User");
        adduser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adduser.setFocusable(false);
        adduser.setOpaque(true);
        adduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adduserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adduserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adduserMouseExited(evt);
            }
        });
        jPanel2.add(adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 250, 60));

        newentry.setBackground(new java.awt.Color(255, 255, 255));
        newentry.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        newentry.setForeground(new java.awt.Color(0, 102, 255));
        newentry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newentry.setText("New Entry");
        newentry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newentry.setFocusable(false);
        newentry.setOpaque(true);
        newentry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newentryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newentryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newentryMouseExited(evt);
            }
        });
        jPanel2.add(newentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 200, 70));

        idcard.setBackground(new java.awt.Color(255, 255, 255));
        idcard.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        idcard.setForeground(new java.awt.Color(51, 102, 255));
        idcard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idcard.setText("User Id Card");
        idcard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idcard.setFocusable(false);
        idcard.setOpaque(true);
        idcard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idcardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                idcardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                idcardMouseExited(evt);
            }
        });
        jPanel2.add(idcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 250, 60));

        userinfo.setBackground(new java.awt.Color(255, 255, 255));
        userinfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        userinfo.setForeground(new java.awt.Color(0, 102, 255));
        userinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userinfo.setText("User Information");
        userinfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userinfo.setFocusable(false);
        userinfo.setOpaque(true);
        userinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userinfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userinfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userinfoMouseExited(evt);
            }
        });
        jPanel2.add(userinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 250, 60));

        inventory.setBackground(new java.awt.Color(255, 255, 255));
        inventory.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inventory.setForeground(new java.awt.Color(0, 102, 255));
        inventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventory.setText("Books Inventory");
        inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventory.setFocusable(false);
        inventory.setOpaque(true);
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryMouseExited(evt);
            }
        });
        jPanel2.add(inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 250, 60));

        returnbook.setBackground(new java.awt.Color(255, 255, 255));
        returnbook.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        returnbook.setForeground(new java.awt.Color(0, 102, 255));
        returnbook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnbook.setText("Return Book");
        returnbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnbook.setFocusable(false);
        returnbook.setOpaque(true);
        returnbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnbookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnbookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnbookMouseExited(evt);
            }
        });
        jPanel2.add(returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 250, 60));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 102, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("Exit");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setFocusable(false);
        exit.setOpaque(true);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 250, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/entry.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 70, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/id.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 60, 60));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 60, 60));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 60, 60));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/return.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 60, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inventory.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 60, 60));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 60, 60));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 880, 440));

        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1090, 520));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Library Management System");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1090, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 120));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/main_page.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 680));

        setSize(new java.awt.Dimension(1107, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnbookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookMouseExited
        Border border = BorderFactory.createLineBorder(new Color(255, 255, 255), 2);
        returnbook.setBorder(border);
    }//GEN-LAST:event_returnbookMouseExited

    private void returnbookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookMouseEntered
        Border border = BorderFactory.createLineBorder(new Color(0, 102, 255), 5);
        returnbook.setBorder(border);
    }//GEN-LAST:event_returnbookMouseEntered

    private void returnbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookMouseClicked
        try {
            new ReturnBook().setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_returnbookMouseClicked

    private void inventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseExited
        Border border = BorderFactory.createLineBorder(new Color(255, 255, 255), 2);
        inventory.setBorder(border);
    }//GEN-LAST:event_inventoryMouseExited

    private void inventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseEntered
        Border border = BorderFactory.createLineBorder(new Color(0, 102, 255), 5);
        inventory.setBorder(border);
    }//GEN-LAST:event_inventoryMouseEntered

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked
        try {
            new Books().setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inventoryMouseClicked

    private void userinfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userinfoMouseExited
        Border border = BorderFactory.createLineBorder(new Color(255, 255, 255), 2);
        userinfo.setBorder(border);
    }//GEN-LAST:event_userinfoMouseExited

    private void userinfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userinfoMouseEntered
        Border border = BorderFactory.createLineBorder(new Color(0, 102, 255), 5);
        userinfo.setBorder(border);
    }//GEN-LAST:event_userinfoMouseEntered

    private void userinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userinfoMouseClicked
        try {
            try {
                new Search().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userinfoMouseClicked

    private void idcardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idcardMouseExited
        Border border = BorderFactory.createLineBorder(new Color(255, 255, 255), 2);
        idcard.setBorder(border);
        //idcard.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_idcardMouseExited

    private void idcardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idcardMouseEntered
        Border border = BorderFactory.createLineBorder(new Color(0, 102, 255), 5);
        idcard.setBorder(border);
        //idcard.setForeground(new Color(0,102,255));
        
    }//GEN-LAST:event_idcardMouseEntered

    private void idcardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idcardMouseClicked
        try {
            new IdCard().setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_idcardMouseClicked

    private void newentryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newentryMouseExited
        Border border = BorderFactory.createLineBorder(new Color(255, 255, 255), 2);
        newentry.setBorder(border);
    }//GEN-LAST:event_newentryMouseExited

    private void newentryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newentryMouseEntered
        Border border = BorderFactory.createLineBorder(new Color(0, 102, 255), 5);
        newentry.setBorder(border);
    }//GEN-LAST:event_newentryMouseEntered

    private void newentryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newentryMouseClicked
        try {
            new BookKeeping().setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newentryMouseClicked

    private void adduserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adduserMouseExited
        Border border = BorderFactory.createLineBorder(new Color(255, 255, 255), 2);
        adduser.setBorder(border);
    }//GEN-LAST:event_adduserMouseExited

    private void adduserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adduserMouseEntered
        Border border = BorderFactory.createLineBorder(new Color(0, 102, 255), 5);
        adduser.setBorder(border);
    }//GEN-LAST:event_adduserMouseEntered

    private void adduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adduserMouseClicked
        try {
            new home().setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adduserMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        Border border = BorderFactory.createLineBorder(new Color(0, 102, 255), 5);
        exit.setBorder(border);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        Border border = BorderFactory.createLineBorder(new Color(255, 255, 255), 2);
        exit.setBorder(border);
    }//GEN-LAST:event_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adduser;
    private javax.swing.JLabel background;
    private javax.swing.JLabel date;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel idcard;
    private javax.swing.JLabel inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel newentry;
    private javax.swing.JLabel returnbook;
    private javax.swing.JLabel time;
    private javax.swing.JLabel userinfo;
    // End of variables declaration//GEN-END:variables
}
